Update FeatureBinarizerFromTrees for compatibility with numpy 1.22.0, scikit-learn 1.0.2, and pandas > 1.3.
Resolve unit test failures, future warnings, and a few minor compatibility issues.

Unit test failures:

    Failure
    Traceback (most recent call last):
      File "tests/rbm/test_Feature_Binarizer_From_Trees.py", line 359, in     test_fit_and_transform_all_feature_classes
        T: DataFrame = fbt.transform(Xn)[0]
    AssertionError: RuntimeWarning not triggered

    Failure
    Traceback (most recent call last):
      File "tests/rbm/test_Feature_Binarizer_From_Trees.py", line 153, in     test_fit_and_transform_exceptions
        fbt.fit(Xn, self.y_train)
    AssertionError: ValueError not raised

scikit-learn raises future warning when passing pandas df with MultiIndex columns to fit(). Reset index to int range before fit().
"FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2."

scikit-learn changed OneHotEncoder to support NaN instead of raising exception. This is incompatible with FeatureBinarizerFromTrees logic. FeatureBinarizerFromTrees.fit() checks for NaNs and raises exception.

numpy no longer raises warnings for NaN/None during vector comparisons. Removed unit test warning assertion.

pandas raises future warnings in set_levels(). Changed syntax appropriately.
"FutureWarning: In a future version of pandas all arguments of MultiIndex.set_levels except for the argument 'levels' will be keyword-only"
"FutureWarning: inplace is deprecated and will be removed in a future version."

Signed-off-by: Floid Gilbert <floidgilbert@gmail.com>